Supply multiple beacon node endpoints.
ConsenSys/doc.teku pull request #386
Opened 2022-08-12 00:10 UTC by bgravenorst

Signed-off-by: bgravenorst <byron.gravenorst@consensys.net>

## Before creating the PR

## Describe the change

We can now configure multiple beacon nodes for a validator client.

## Issue fixed

Fixes #384 

## Preview

2022-08-17 09:07 UTC, StefanBratanov requested changes
LGTM

2022-08-17 09:07 UTC, StefanBratanov commented on docs/Reference/CLI/Subcommands/Validator-Client.md
> +    TEKU_BEACON_NODE_ENDPOINT=http://192.138.10.12,http://192.140.11.44:5051
Should it not be TEKU_BEACON_NODE_API_ENDPOINT?

2022-08-17 21:16 UTC, alexandratran approved these changes
Minor suggestion. LGTM.

2022-08-17 21:16 UTC, alexandratran commented on docs/HowTo/Get-Started/Run-Teku.md
> +    primary node, and others as failovers.
```suggestion
    You can supply multiple beacon node endpoints to the validator. The first one is used as the
    primary node, and others as failovers.
```

2022-08-17 21:16 UTC, alexandratran commented on docs/Reference/CLI/Subcommands/Validator-Client.md
> +If multiple beacon node endpoints are configured, the first one will be used as primary and others
```suggestion
If multiple beacon node endpoints are configured, the first one is used as primary and others
```

2022-08-18 18:17 UTC, StefanBratanov approved these changes
LGTM

2022-08-18 18:17 UTC, merged